### ISSUE TITLE
 A question

### ISSUE THREAD

**Issue by wojtulinka** [gaycookie/Transparent-Cosmetics#1]

**Comment by wojtulinka** [comment]
Hey! Could you make a client-side mod that toggles visuality of armor? I wanna see my skin while wearing netherite armor on a 1.18 server. I'd love this so much. Thanks dude!

**Comment by gaycookie** [comment]
Thank you! 🥰

At this current moment, this is not possible with this mod.
But I've (when I get to it) plans to make a full standalone version that does this.
It will be a client-side only mod.

More details will follow when I start on it and release it.
