### ISSUE TITLE
plz update modrinth release

### ISSUE THREAD

**Issue by yesn0t** [gaycookie/Transparent-Cosmetics#4]
hello, thanks for updating this mod, i'd be glad if you could upload version 1.3.0 to modrinth x)  
currently newest version of this mod in modrinth is 1.2.0 (1.16.5) https://modrinth.com/mod/transparent-cosmetics/versions

**Comment by gaycookie** [comment]
Hello @yesn0t,

I'm sorry, I totally forgot that I used Modrinth.
I'll do my best do have it updated tonight!

Greet

**Comment by gaycookie** [comment]
The Modrinth page has been updated!

Keep in mind; 1.4.0 works on 1.18.**2** but only when Cosmetic Armor also will be updated to 1.18.**2**.
Since that one is that this current moment only ported to 1.18 and 1.18.1.

Have funs!

**Comment by yesn0t** [comment]
thank you and for the heads up :pray: i'll keep that in mind
