### ISSUE TITLE
Small visual issue

### ISSUE THREAD

**Issue by Llamacorn123** [gaycookie/Transparent-Cosmetics#5]
Everything works fine but the boobs of the Wildfire's Female Gender Mod (link is: https://www.curseforge.com/minecraft/mc-mods/female-gender-fabric)
![2022-04-15_16 26 07](https://user-images.githubusercontent.com/41273674/163629198-1428b082-9947-42dc-ab6a-583137e26401.png)

**Comment by gaycookie** [comment]
Hello,

I'm afraid I won't be able to do much about this since this is not in my controll.
You might be better off by contacting the developer for said mod.

I'll keep this open if you have other questions/info related to this.
