### ISSUE TITLE
[Update] for 1.19.x <3

### ISSUE THREAD

**Issue by xR4YM0ND** [gaycookie/Transparent-Cosmetics#8]

**Comment by douglasparker** [comment]
It looks like it was ported in MR #7 but it actually hasn't been released on Modrinth and CurseForge.

@gaycookie any update on this by chance?

**Comment by gaycookie** [comment]
Hello @douglasparker,

Tomorrow, I will take a thorough look at everything. It's been quite some time since I last worked on Minecraft development, so perhaps it's time for me to pick it up again.

I plan to initiate a re-run, and publish the updates to Modrinth and CurseForge tomorrow as well.

**Comment by douglasparker** [comment]
> Hello @douglasparker,
> 
> Tomorrow, I will take a thorough look at everything. It's been quite some time since I last worked on Minecraft development, so perhaps it's time for me to pick it up again.
> 
> I plan to initiate a re-run, and publish the updates to Modrinth and CurseForge tomorrow as well.

That sounds great! Thanks for the update!

**Comment by gaycookie** [comment]
You're in luck because I'm actually in the process of transitioning away from GitHub, haha. I only check GitHub occasionally, and today happened to be one of those days, coincidentally.

Currently, my Minecraft projects will remain on GitHub, but that may change in the future. If I do switch to a new Git platform, rest assured that I will update the projects accordingly.

**Comment by douglasparker** [comment]
> You're in luck because I'm actually in the process of transitioning away from GitHub, haha. I only check GitHub occasionally, and today happened to be one of those days, coincidentally.
> 
> Currently, my Minecraft projects will remain on GitHub, but that may change in the future. If I do switch to a new Git platform, rest assured that I will update the projects accordingly.

Ah, gotcha!

What platform are you transitioning to?

Definitely let us know when your projects are moving and where!

> Edit: Rerun should be done now and have new artifacts. 

Awesome, thank you so much I appreciate it! ☺️

**Comment by gaycookie** [comment]
A combination between Gitlab and my own Gitea instance.

**Comment by gaycookie** [comment]
I'm just checking the Artifacts and I'm really curious if this actually worked for anyone?
I seem to have issues running it, I almost feel like I'm doing something wrong haha.

**Comment by douglasparker** [comment]
> I'm just checking the Artifacts and I'm really curious if this actually worked for anyone?
> I seem to have issues running it, I almost feel like I'm doing something wrong haha.

I haven't had the chance to test it, but assuming the PR was good it should be fine.

Most people aren't checking GitHub for Minecraft releases so I highly recommend it be uploaded to Modrinth and CurseForge.

**Comment by gaycookie** [comment]
Yes, I get you but problem is..  I'm not uploading borked mods haha.
I'm reinstalling my IDE again and gonna check out what the error is about.
I hope nothing has changed in Fabric.. or else this gonna be a long evening xD

**Comment by douglasparker** [comment]
> Yes, I get you but problem is..  I'm not uploading borked mods haha.
> I'm reinstalling my IDE again and gonna check out what the error is about.
> I hope nothing has changed in Fabric.. or else this gonna be a long evening xD

Oh, I understand now. I thought the code was tested and reviewed before being merged.

**Comment by gaycookie** [comment]
I thought so too or else I wouldn't have merged it indeed.. But somehow I can't get it to work with 1.19.3 and 1.19.4.
So I'm curious if its my doing with my OpenJDK or if its just the mod being fucked now and I really have to fix it.

**Comment by douglasparker** [comment]
> I thought so too or else I wouldn't have merged it indeed.. But somehow I can't get it to work with 1.19.3 and 1.19.4.
> So I'm curious if its my doing with my OpenJDK or if its just the mod being fucked now and I really have to fix it.

I'm not a mod developer but I heard that mods were broken between 1.19.x releases despite being bugfix point releases based on the server spec.

You'd think the API would be backwards compatible but from what I've read that is not the case.

**Comment by gaycookie** [comment]
That explains a lot why Trinkets has like almost a new version for every 1.19 release haha.

**Comment by gaycookie** [comment]
I've just published a new branch that should work with at least 1.19.4 as far as I've been able to test, if you got some time I would love to hear if it works for you too!

**Comment by douglasparker** [comment]
> That explains a lot why Trinkets has like almost a new version for every 1.19 release haha.
> If this is the case, I will only target 1.19.4, since that is the last version.

Ah, I just read this. Most mods skipped 1.19.4 because it broke so many of them.

1.19.2 seems to be the version of Minecraft with the most mod support. Mod devs seem to be skipping 1.19.4 and going directly to 1.20 once it releases.

Unfortunately, I can't test for 1.19.4 since my community plays on 1.19.2.

**Comment by xR4YM0ND** [comment]
Same here, we're on 1.19.2 & next up will be 1.20

**Comment by gaycookie** [comment]
Lets continue this in https://github.com/gaycookie/Transparent-Cosmetics/issues/10 so this one can stay closed haha!
The plan to let me work on updates has worked 😂
